# syntax=docker/dockerfile:1
FROM python:3.14-slim@sha256:a7185a8e40af01bf891414a4df16ef10fc6000cee460a404a13da9029fe41604
WORKDIR /app

RUN pip install --no-cache-dir uv && \
    uv sync --dev

EXPOSE 8080

CMD ["python", "-m", "src.serving.api_server", "--host", "0.0.0.0", "--port", "8080"]
